# Baseline model template (SASRec or BERT4Rec)
model_type: sasrec  # or bert4rec
dataset: ml20m  # ml20m, beauty, kion_en, amazon_m2

# Data paths
train_sequence_file: data/train_sequences.json
valid_sequence_file: data/valid_sequences.json
test_sequence_file: data/test_sequences.json
item_map_file: data/item_map.json

# Model parameters
hidden_units: 64
num_blocks: 2
num_heads: 2
dropout_rate: 0.2
maxlen: 50

# Training parameters
batch_size: 128
learning_rate: 0.001
epochs: 200
early_stopping: 10
eval_every: 5
eval_from: 50
save_model: true

# Sampling parameters
use_neg_sampling: true
sample_size: 100

# Other parameters
seed: 42
device: cuda
verbose: true