# experiments/configs/sasrec.yaml

seed: 1

model:
  model_name: SASRec
  item_num: 0  # Значения будут обновлены в коде
  user_num: 0
  maxlen: 50
  hidden_units: 64
  num_blocks: 2
  num_heads: 2
  dropout_rate: 0.2
  add_head: true

training:
  batch_size: 256
  epochs: 30
  learning_rate: 0.001
  eval_every: 1
  model_dir: models/

data:
  profile_train_sequences: data/processed/train_sequences.pkl
  finetune_train_sequences: data/processed/train_sequences.pkl
  valid_sequences: data/processed/valid_sequences.pkl
  test_sequences: data/processed/test_sequences.pkl
  mappings: data/processed/mappings.pkl
  counts: data/processed/counts.pkl
  user_profile_embeddings_path: data/emb/embedding_kion.json  # Путь к эмбеддингам профилей пользователей

experiment_name: "baseline"
