# experiments/configs/sasrec.yaml

seed: {seed}

model:
  model_name: SASRec
  item_num: 0  # Значения будут обновлены в коде
  user_num: 0
  maxlen: 50
  hidden_units: {hidden_units}
  num_blocks: {num_blocks}
  num_heads: {num_heads}
  dropout_rate: {dropout_rate}
  add_head: true

training:
  batch_size: 256
  epochs: {epochs}
  learning_rate: {learning_rate}
  eval_every: 1
  model_dir: models/

data:
  profile_train_sequences: {profile_train_sequences}
  finetune_train_sequences: {finetune_train_sequences}
  valid_sequences: {valid_sequences}
  test_sequences: {test_sequences}
  mappings: {mappings}
  counts: {counts}
  user_profile_embeddings_files: {user_profile_embeddings_files}

experiment_name: "{experiment_name}"
